.cargo/config, src/lib.rs, src/runtime.rs
Rustdoc doesn't render "feature required" alerts on `pub use` reexports (even when those reexports aren't presented as reexports). To work around this, the `doc(cfg(...))` attr needs to also be applied to the actual item definitions.
=> fix 'feature requires' notices

src/task.rs
notable changes:
- fixed a broken snippet (used `rust=` as the language)
- "period" -> "interval", for consistency
- removed mention of `mean_extant_duration`, a metric that does not yet exist
=> More documentation polish.

src/lib.rs, src/runtime.rs
Using return-position-impl-trait for the iterator returned by `RuntimeMonitor::intervals` means that users can't name the type to store it without boxing the iterator. I'd like to be able to do that in a [crate to add Prometheus integration][tokio-metrics-prometheus] ideally (although boxing isn't really the end of the world there).
[tokio-metrics-prometheus]: https://github.com/sd2k/tokio-metrics-prometheus
=> Add concrete `RuntimeMetricsIter` type

src/runtime.rs, src/task.rs
=> Add `Debug` implementations.

Cargo.toml, examples/stream.rs, src/task.rs
Using pretty much the same logic as for futures, instrument streams as
well.
Fixes #30
=> task: also instrument streams

README.md, src/runtime.rs, src/task.rs
- `steal_count` falsely claimed to be the number of times tasks were stolen, but was actually the number of tasks stolen. Adjust the documentation to reflect this fact
- ~~Expose the new `steal_operations` metric, which tracks what was previously documented to be `steal_count`. This requires [#5330](https://github.com/tokio-rs/tokio/pull/5330), so I guess it might make sense for me to split that part into a separate PR since it requires bumping the minimum supported tokio version.~~ Edit: Removed this part and kept only the documentation changes.
=> Fix the description of steal_count

Cargo.toml, src/runtime.rs, src/task.rs
Adds the recent metric and bumps the tokio version to 1.26.0
=> rt: add budget_forced_yield_count metric

Cargo.toml, README.md, src/runtime.rs
Follow-up to https://github.com/tokio-rs/tokio-metrics/pull/35.
The new metric is available starting with tokio v1.25.0.
Would it be okay to just bump the required tokio version and release a new tokio-metrics version? Or would you prefer something more advanced like version detection in a build script?
Edit: A different PR bumped the required tokio version already. Rebased.
=> Add steal_operations metric

CHANGELOG.md, Cargo.toml, README.md
- Add `Debug` implementations. ([#28])
- rt: add concrete `RuntimeIntervals` iterator type ([#26])
- rt: add budget_forced_yield_count metric ([#39])
- rt: add io_driver_ready_count metric ([#40])
- rt: add steal_operations metric ([#37])
- task: also instrument streams ([#31])
- doc: fix count in `TaskMonitor` docstring ([#24])
- doc: the description of steal_count ([#35])
[#24]: https://github.com/tokio-rs/tokio-metrics/pull/24
[#26]: https://github.com/tokio-rs/tokio-metrics/pull/26
[#28]: https://github.com/tokio-rs/tokio-metrics/pull/28
[#31]: https://github.com/tokio-rs/tokio-metrics/pull/31
[#35]: https://github.com/tokio-rs/tokio-metrics/pull/35
[#37]: https://github.com/tokio-rs/tokio-metrics/pull/37
[#39]: https://github.com/tokio-rs/tokio-metrics/pull/39
[#40]: …
=> chore: prepare v0.2.0

README.md, src/task.rs
This adds short and long scheduler delay metrics, paralleling fast and slow poll metrics.
=> task: add short and long delay metrics

CHANGELOG.md, Cargo.toml, README.md
- task: add short and long delay metrics ([#44])
[#44]: https://github.com/tokio-rs/tokio-metrics/pull/44
=> chore: release v0.2.1

CHANGELOG.md, Cargo.toml, README.md
- task: add TaskMonitorBuilder ([#46])
- task: fix default long delay threshold ([#46])
[#46]: https://github.com/tokio-rs/tokio-metrics/pull/46
=> chore: release v0.2.2

Cargo.toml, src/runtime.rs
Exposes the mean poll duration metric exposed by Tokio 1.31.
=> rt: support mean poll duration metric

Cargo.toml
Tokio 1.33 has removed the `stats` feature, which apparently was unused for quite a bit.
I'm not sure how this repo manages releases, so feel free to consider this PR as an issue if you'd rather approach the problem differently. Thanks!
=> support tokio 1.33 without stats feature

CHANGELOG.md, Cargo.toml, README.md
- task: fix doc error in idle definition ([#54])
- chore: support tokio 1.33 without stats feature ([#55])
[#54]: https://github.com/tokio-rs/tokio-metrics/pull/54
[#55]: https://github.com/tokio-rs/tokio-metrics/pull/55
=> chore: release v0.3.1

CHANGELOG.md, Cargo.toml, README.md
The core Tokio crate has renamed some of the metrics and this breaking release uses the new names. The minimum required Tokio is bumped to 1.41, and the MSRV is bumped to 1.70 to match.
- runtime: use new names for poll time histogram ([#66])
- runtime: rename injection queue to global queue ([#66])
- doc: various doc fixes ([#66], [#65])
[#65]: https://github.com/tokio-rs/tokio-metrics/pull/65
[#66]: https://github.com/tokio-rs/tokio-metrics/pull/66
=> chore: prepare 0.4.0

README.md, src/runtime.rs, src/runtime/metrics_rs_integration.rs
Added more metrics from [tokio](https://docs.rs/tokio/latest/tokio/runtime/struct.RuntimeMetrics.html) to tokio-metrics.
Fixes #61.
=> feat: add more metrics

CHANGELOG.md, Cargo.toml, README.md
- rt: add support for `blocking_queue_depth`, `live_task_count`, `blocking_threads_count`,
`idle_blocking_threads_count` ([#49], [#74])
- rt: add integration with metrics.rs ([#68])
[#49]: https://github.com/tokio-rs/tokio-metrics/pull/49
[#68]: https://github.com/tokio-rs/tokio-metrics/pull/68
[#74]: https://github.com/tokio-rs/tokio-metrics/pull/74
=> chore: prepare 0.4.1

.gitignore, CONTRIBUTING.md, src/lib.rs, src/runtime.rs
Still need to test locally - just was getting the PR open before closing up for the day :)
=> fix: rt: in docs.rs, annotate the module as requiring `metrics-rs-integration` along with `rt` and `tokio_unstable`

CHANGELOG.md, README.md
=> chore: prepare 0.4.3

src/task.rs
From similar motivation in https://github.com/tokio-rs/tokio-metrics/pull/26 , this PR introduces `TaskIntervals` as a concrete type.
FYI, my use case for the struct is implementing integration of TaskMonitor with metrics-rs (https://github.com/tokio-rs/tokio-metrics/issues/71)
=> fix: Add `TaskIntervals` struct
